version: '3'
services:
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        env_file: 
            - .env
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_HOST: ${DATABASE_HOST}
            POSTGRES_PORT: ${DATABASE_PORT}

    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - .:/test-sehatqu
        ports:
            - "3001:3000"
        depends_on:
            - db
        env_file: 
            - .env
        environment: 
            RAILS_ENV: ${RAILS_ENV}
            RACK_ENV: ${RACK_ENV}      
